### ISSUE TITLE
telephonyspamprotect-pa.googleapis.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#11]
Hi,
This domain is needed for Android's telephone spam protect feature
While this domain is blocked, I recieved SMS spam texts that I did not get while it wasn;t blocked

**Comment by RooneyMcNibNug** [comment]
Hi, 

Thanks for submitting this. I meant to add this to my personal blacklist (I don't trust this Google filtering for "spam", similar to their safebrowsing domain stuff) but I will remove this from the SNAFU blocklist for you and others, so that the choice is not on my end. It has now been removed with the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/4eb844943dac9f90fd376726d22f7da19fadd96d

- JA
