### ISSUE TITLE
carto.com

### ISSUE THREAD

**Issue by aureq** [RooneyMcNibNug/pihole-stuff#41]
Hi

I noticed I had to selectively allow `dhhs.carto.com` and `gusc.ep.carto.com` which are similar to Google Maps.
Is it a false positive or is it expected ?

Thanks

**Comment by RooneyMcNibNug** [comment]
Hi, 

Thank you very much for this issue.

I originally enumerated this domain intentionally, I think because the service describes part of its product "Location Intelligence platform allows organizations to store, enrich, analyze & visualize their data to make spatially-aware decisions." and includes creepy uses like "Mastercard Advisors uses CARTO to turn millions of daily credit card transactions into location-based insights for B2B clients in Retail, Real Estate and the Public Sector" (this is all listed on the main `carto.com` page.

However, I do want to make this list "friendly" for anyone who wants to use it, so can you let me know if this is fundamentally breaking another page or service from functioning for you? If you don't mind sharing a bit more detail? I will remove the full enum if this is the case.

Regards,
_Rooney_

**Comment by aureq** [comment]
Hi @RooneyMcNibNug Thanks a lot for your reply and it makes a lot of sense.

I've come across the issue while visiting the [Victoria Travel Permit System](https://www.coronavirus.vic.gov.au/victorian-travel-permit-system) page. On the page, there's an `iframe` that embeds this [page / map](https://dhhs.carto.com/builder/045f781d-be13-428c-88ab-3a2f4f88e0f2/embed).

I looked into the [dns resolution](https://www.digwebinterface.com/?hostnames=dhhs.carto.com+&type=&colorize=on&ns=resolver&useresolver=8.8.4.4&nameservers=) for `dhhs.carto.com` and I found it pointed to `gusc.ep.carto.com` via a `CNAME` so I had to manually remove both from my deny list.

I hope this helps.

Best
Aurel

**Comment by RooneyMcNibNug** [comment]
Ah, I see the iframe now on there. That makes sense. 

I'm actually looking more carefully at this enumeration now and I am seeing a lot of seemingly legitimate subdomains here, so I am going to solve this by removing all of the `*.carto.com` domains in the list **except** for the following:

```
groupmarketing.carto.com
status.carto.com
stolenride.carto.com
twitterdata.carto.com
```

I believe these to be used for user tracking and/or marketing purposes, but if you run into any other issues with `carto.com` elements on pages please do let you know.

This issue has been solved with the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/07fc5834ba494f75198ffefaa3bca80a400b25d9

Again, thanks so much for contributing, and stay safe.
_Rooney_

**Comment by aureq** [comment]
Perfect. Thank you very much for your quick action.
