### ISSUE TITLE
transactions.sendowl.com

### ISSUE THREAD

**Issue by p1r473** [RooneyMcNibNug/pihole-stuff#42]
This site allows downloads for purchased content from small developers and creators

**Comment by RooneyMcNibNug** [comment]
Hi @p1r473 ,

Thanks for reporting this issue. I do appreciate it.

I have gone ahead and removed `transactions.sendowl.com` from the blocklist, but am going to keep the following URLs from the same domain, as I believe them to be for tracking purposes:

```
metrics.sendowl.com
stats.sendowl.com
```

If you think that there are further issues being caused by these remaining subdomains, please do let me know if you can.

This has been done in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/c13aaac1650559c8c19590fb93d88a10fa5950a1

Stay safe out there, 
_Rooney_
