### ISSUE TITLE
False positive: Ayden payment provider

### ISSUE THREAD

**Issue by nlhans** [RooneyMcNibNug/pihole-stuff#46]
A large fast-food store uses Adyen* as payment provider for use with iDeal, which sounds like a false positive.

It was added, along with a large bunch of other domains from Adyen*, in this commit:

https://github.com/RooneyMcNibNug/pihole-stuff/commit/dc3338782332c5f668790f07f5216b8f65c2cdde#diff-a452d476c2e2bbc2a88a8c8823185bf2b2413ba4a7bc79611923ab1ee8e35fd2R55610

**Comment by RooneyMcNibNug** [comment]
Hi @nlhans ! Thank yoiu for submitting this issue, it is much appreciated.

I have gone ahead and removed the _entire_ `adyen.com` subdomain, as I don't see a good enough reason to keep any of those URLs around on the list. This should clear up your mentioned issues, but let me know if it doesn't due to some other URL(s) on the list.

This has been completed with the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/33389fe27097ccddaf2ee6d7f1687401044cdda3

Safe Surfin.
