### ISSUE TITLE
Is usercentrics.eu false positive?

### ISSUE THREAD

**Issue by bronger** [RooneyMcNibNug/pihole-stuff#62]
You cannot use user-related forms on the German webpage of the World Wildlife Fund (WWF) with your pihole list.  In particular, blocking of usercentrics.eu prevents the web form on https://www.wwf.de/spenden-helfen/mitgliederservice/adresse-aendern from working.

A short visit of the companies website let me suspect that it is a good service, in fact caring about privacy. Besides, I assume that the WWF selects its partners carefully. Still, you cannot look inside what’s happening usercentrics.eu.

So I cannot recommend to remove that from your list, just to ask for a review. I myself will whitelist it.

**Comment by RooneyMcNibNug** [comment]
Hi @bronger , 

Since this is messing up some forms I think I am going to ditch it from my list, since this is about blocking as much as possible while not breaking anything.

This has been removed in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/4a24e7bcf0970795d503e23d473003d0bb95ba4d

so no need to whitelist on your end.

Thanks again, and safe travels.
_Rooney_
