### ISSUE TITLE
target.scene7.com

### ISSUE THREAD

**Issue by vmstan** [RooneyMcNibNug/pihole-stuff#9]
Blocking this breaks the Target store's iOS app, none of the images will load.

**Comment by RooneyMcNibNug** [comment]
Thank you for this ticket. 

I have removed `target.scene7.com` as well as numerous other `scene7.com` subdomains from my list in order to prevent app and/or site breakage. This has been completed in the following commit: https://github.com/RooneyMcNibNug/pihole-stuff/commit/f87682a06d1aeba1832987773bb3b28fa9994069
